[project]
name = "competition"
version = "4.1.36"
description = "Competition shared dependencies"
authors = [{ name = "tpn.xyz" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common",
    "huggingface_hub>=0.23.0",
    "requests>=2.31.0",
    "loguru>=0.7.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.uv.sources]
common = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/competition"]
